In [1]:
a=[4,22,21,23,77,4545,453,342,4646,67,5543,325,356,213,99,323,543,325,634,12,1,435]
b=[]
maximum=max(a)
mininum=min(a)
for i in a:
    b=(i-minimum)/(maximum-minimum)
print(b)

NameError: name 'minimum' is not defined

In [3]:
a=[4,22,21,23,77,4545,453,342,4646,67,5543,325,356,213,99,323,543,325,634,12,1,435]
b=[]
maximum=max(a)
minimum=min(a)
for i in a:
    b.append((i-minimum)/(maximum-minimum))
print(b)

[0.0005413208228076507, 0.0037892457596535546, 0.003608805485384338, 0.003969686033922772, 0.013713460844460484, 0.8199206062793215, 0.08155900396968603, 0.06153013352580296, 0.8381450739805124, 0.011909058101768314, 1.0, 0.058462648863226274, 0.064056297365572, 0.03825333814507398, 0.017683146878383255, 0.058101768314687836, 0.09779862865391556, 0.058462648863226274, 0.1142186936124143, 0.001984843016961386, 0.0, 0.07831107903284013]


In [4]:
from numpy import asarray
from sklearn preprocessing import MinMaxScaler
data=asarray([[100,0.001][8,0.05],[50,0.005],[88,0.007],[4,0.1]])
scaler=MinMaxScaler()
Scaled=scaler.fit-transform(data)
print(Scaled)

SyntaxError: invalid syntax (<ipython-input-4-7ace8478d7d0>, line 2)

In [5]:
!pip install sklearn


ERROR: Could not find a version that satisfies the requirement sklearn (from versions: none)
ERROR: No matching distribution found for sklearn


In [6]:
import sklearn

In [7]:
from numpy import asarray
from sklearn.preprocessing import MinMaxScaler
data=asarray([[100,0.001][8,0.05],[50,0.005],[88,0.007],[4,0.1]])
scaler=MinMaxScaler()
Scaled=scaler.fit_transform(data)
print(Scaled)

<>:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-7-50486178e071>:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  data=asarray([[100,0.001][8,0.05],[50,0.005],[88,0.007],[4,0.1]])


TypeError: list indices must be integers or slices, not tuple

In [8]:
from numpy import asarray
from sklearn.preprocessing import MinMaxScaler
data=asarray([[100,0.001],[8,0.05],[50,0.005],[88,0.007],[4,0.1]])
scaler=MinMaxScaler()
Scaled=scaler.fit_transform(data)
print(Scaled)

[[1.         0.        ]
 [0.04166667 0.49494949]
 [0.47916667 0.04040404]
 [0.875      0.06060606]
 [0.         1.        ]]


In [9]:
from numpy import asarray
from sklearn.preprocessing import MinMaxScaler
data=asarray([[10,0.06][800,0.5],[500,0.5],[88,0.007],[47,0.7]])
scaler=MinMaxScaler()
Scaled=scaler.fit_transform(data)
print(Scaled)

<>:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-9-d0ecc581d760>:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  data=asarray([[10,0.06][800,0.5],[500,0.5],[88,0.007],[47,0.7]])


TypeError: list indices must be integers or slices, not tuple

In [10]:
from numpy import asarray
from sklearn.preprocessing import MinMaxScaler
data=asarray([[10,0.06],[800,0.5],[500,0.5],[88,0.007],[47,0.7]])
scaler=MinMaxScaler()
Scaled=scaler.fit_transform(data)
print(Scaled)

[[0.         0.07647908]
 [1.         0.71139971]
 [0.62025316 0.71139971]
 [0.09873418 0.        ]
 [0.04683544 1.        ]]


In [11]:
a=[[10,0.06],[800,0.5],[500,0.5],[88,0.007],[47,0.7]]
b=[]
maximum=max(a)
mininum=min(a)
for i in a:
     b.append((i-minimum)/(maximum-minimum))
print(b)

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [12]:
a=[[10,0.06],[800,0.5],[500,0.5],[88,0.007],[47,0.7]]
b=[[]]
maximum=max(a)
mininum=min(a)
for i in a:
    for j in i:
             b.append((j-minimum)/(maximum-minimum))

print(b)

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [13]:
a=[[10,0.06],[800,0.5],[500,0.5],[88,0.007],[47,0.7]]
maximum=max([max(i) for i in a ])
minimum=min([min(j) for j in a ])
for i in a:
    for j in i:
             print((j-minimum)/(maximum-minimum))


0.01249135929939387
6.62505796925723e-05
1.0
0.000616255392234682
0.6249967187212888
0.000616255392234682
0.10999221243185876
0.0
0.05874176399043492
0.0008662575797538227


In [14]:
from numpy import asarray
from sklearn.preprocessing import Normalizer
data=asarray([[10,0.06],[800,0.5],[500,0.5],[88,0.007],[47,0.7]])
scaler=Normalizer()
Scaled=scaler.fit_transform(data)
print(Scaled)

[[9.99982000e-01 5.99989200e-03]
 [9.99999805e-01 6.24999878e-04]
 [9.99999500e-01 9.99999500e-04]
 [9.99999997e-01 7.95454543e-05]
 [9.99889109e-01 1.48919654e-02]]


In [15]:
from numpy import asarray
from sklearn.preprocessing import Normalizer
data=asarray([[100,0.001],[8,0.05],[50,0.005],[88,0.007],[4,0.1]])
scaler=Normalizer()
Scaled=scaler.fit_transform(data)
print(Scaled)

[[1.00000000e+00 1.00000000e-05]
 [9.99980469e-01 6.24987793e-03]
 [9.99999995e-01 9.99999995e-05]
 [9.99999997e-01 7.95454543e-05]
 [9.99687646e-01 2.49921912e-02]]


In [16]:
import statistics as st
a=[-3,-2,-1,0,1,2,3]
i=st.mean()
print(i)

TypeError: mean() missing 1 required positional argument: 'data'

In [17]:
import statistics as st
a=[-3,-2,-1,0,1,2,3]
i=st.mean(a)
print(i)

0


In [18]:
import statistics as st
a=[-3,-2,-1,0,1,2,3]
i=st.variance(a)

print(i)

4.666666666666667


In [25]:
import statistics as st
from sklearn.preprocessing import StandardScaler

a=[0,1,2,3,4,5,6]
b=st.stdev(a)
c=st.mean(a)

for i in a:
    print((i-c)/b)
    
scaler=StandardScaler()
Scaled=scaler.fit_transform(a)
print(Scaled)

-1.3887301496588271
-0.9258200997725514
-0.4629100498862757
0.0
0.4629100498862757
0.9258200997725514
1.3887301496588271


ValueError: Expected 2D array, got 1D array instead:
array=[0. 1. 2. 3. 4. 5. 6.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [26]:
from numpy import asarray
from sklearn.preprocessing import StandardScaler
data=asarray([[10,0.06],[800,0.5],[500,0.5],[88,0.007],[47,0.7]])
scaler=StandardScaler()
Scaled=scaler.fit_transform(data)
print(Scaled)

[[-0.89818118 -1.07974062]
 [ 1.64505585  0.5395023 ]
 [ 0.67926964  0.5395023 ]
 [-0.64707676 -1.27478579]
 [-0.77906755  1.27552181]]
